### ISSUE TITLE
Ошибка при скачивании страницы: bad content length

### ISSUE THREAD

**Issue by astoriawinter** [lirix360/ReadmangaGrabber#85]
Привет, спасибо за полезную утилиту!
Есть проблема, что некоторые главы некорректно подтягиваются, и процесс прерывается на середине.
Стектрейс: 
```
2023-07-28 21:37:26	[ERR]:	(mangalib.go:294):	Ошибка при скачивании страницы: bad content length
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1543be0]

goroutine 98 [running]:
github.com/lirix360/ReadmangaGrabber/mangalib.DownloadChapter({{0xc00029a3a0, 0x8}, {0xc000110840, 0x15b}, {0xc0000d00c0, 0x33}, {0xc00029a3f7, 0x1}, {0xc00029a403, 0x1}, ...}, ...)
	/mnt/e/Dev/go/src/github.com/lirix360/ReadmangaGrabber/mangalib/mangalib.go:299 +0xda0
github.com/lirix360/ReadmangaGrabber/mangalib.DownloadManga({{0xc00029a3a0, 0x8}, {0xc000110840, 0x15b}, {0xc0000d00c0, 0x33}, {0xc00029a3f7, 0x1}, {0xc00029a403, 0x1}, ...})
	/mnt/e/Dev/go/src/github.com/lirix360/ReadmangaGrabber/mangalib/mangalib.go:153 +0x518
created by github.com/lirix360/ReadmangaGrabber/manga.DownloadManga
	/mnt/e/Dev/go/src/github.com/lirix360/ReadmangaGrabber/manga/manga.go:97 +0x3b8
```
Отловить можно например если попытаться скачать https://mangalib.me/ag-yeog-uiending-eunjug-eumppun, v3/c95
С сайта все качается напрямую без проблем.

**Comment by progzone122** [comment]
Тот же баг всплыл
